version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app:/var/www/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    networks:
      - network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - composer
    networks:
      - network

  database:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: install

networks:
  network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mysql_data: